CREATE TABLE `jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`jobId` varchar(78) NOT NULL,
	`contractAddress` varchar(42) NOT NULL,
	`chainId` int NOT NULL,
	`txHash` varchar(66),
	`clientAddress` varchar(42) NOT NULL,
	`providerAddress` varchar(42),
	`evaluatorAddress` varchar(42),
	`title` varchar(200) NOT NULL,
	`description` text,
	`tokenAddress` varchar(42) NOT NULL,
	`tokenSymbol` varchar(20) DEFAULT 'ETH',
	`amount` varchar(78) NOT NULL,
	`state` enum('open','funded','submitted','completed','rejected','expired','cancelled') NOT NULL DEFAULT 'open',
	`deliverableHash` varchar(66),
	`deliverableUrl` text,
	`rejectReason` text,
	`expiryAt` timestamp,
	`fundedAt` timestamp,
	`submittedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jobs_id` PRIMARY KEY(`id`),
	CONSTRAINT `jobs_jobId_unique` UNIQUE(`jobId`)
);
--> statement-breakpoint
CREATE TABLE `wallet_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`walletAddress` varchar(42) NOT NULL,
	`displayName` varchar(100) NOT NULL,
	`role` enum('client','provider','evaluator') NOT NULL,
	`bio` text,
	`chainId` int DEFAULT 11155111,
	`isVerified` boolean DEFAULT false,
	`jobsCreated` int DEFAULT 0,
	`jobsCompleted` int DEFAULT 0,
	`reputation` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `wallet_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `wallet_profiles_walletAddress_unique` UNIQUE(`walletAddress`)
);
